"""
FCC lattice definitions for the cellular-automata simulator.

The simulator stores fields in dense 3D textures indexed by ``ivec3``. A
lattice specifies how those integer indices map to world-space positions and
what the nearest-neighbour offsets are.

This module defines the face-centred-cubic (FCC) lattice that replaces the
legacy cubic lattice. The legacy cubic implementation is preserved at the
``pre-fcc-transition`` git tag; nothing in this module is backward compatible
with it.

Design choices
--------------
* **Dense native storage.** Texture shape is ``(Na, Nb, Nc)``. Every texel
  is a real lattice cell. There is no parity bit, no validity test, no wasted
  memory. The index-space lookup ``texelFetch(tex, ivec3(a,b,c))`` is the
  cell at primitive-cell coordinate ``(a, b, c)``.

* **Primitive cell basis.** The three primitive vectors are the shortest
  lattice translations of FCC. In units where the nearest-neighbour distance
  equals 1::

      v1 = (1, 1, 0) / sqrt(2)
      v2 = (0, 1, 1) / sqrt(2)
      v3 = (1, 0, 1) / sqrt(2)

  All three have unit length (they ARE nearest-neighbour vectors). The
  ordering is chosen so the basis is right-handed (``det(M) > 0``).

* **Twelve nearest neighbours in index space.** Because each ``v_i`` is a
  nearest neighbour, so is each ``v_i - v_j``. That yields exactly 12
  unit-length displacements::

      6 "axial":    +-v1, +-v2, +-v3              -> +-(1,0,0), +-(0,1,0), +-(0,0,1)
      6 "diagonal": +-(v_i - v_j) for i < j       -> +-(1,-1,0), +-(0,1,-1), +-(1,0,-1)

  All twelve are stored as ``int8`` offsets and emitted to GLSL as a
  ``const ivec3[12]`` table.

* **GLSL header.** Generated by :func:`glsl_header`. Provides macros and
  constants every shader needs: neighbour count, neighbour table, the
  index-to-world matrix, its inverse, and the primitive cell volume.

* **No runtime polymorphism.** There is one lattice (FCC). If BCC or another
  lattice is added later, refactor into an interface then. YAGNI for now.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Tuple

import numpy as np


# ---------------------------------------------------------------------------
# Primitive vectors (columns of M). Right-handed, unit-length.
# ---------------------------------------------------------------------------

_SQRT2_INV = 1.0 / np.sqrt(2.0)

# Columns are v1, v2, v3. ``world = M @ index``.
_M = np.array(
    [
        [_SQRT2_INV, 0.0,        _SQRT2_INV],
        [_SQRT2_INV, _SQRT2_INV, 0.0       ],
        [0.0,        _SQRT2_INV, _SQRT2_INV],
    ],
    dtype=np.float64,
)
_M_INV = np.linalg.inv(_M)
_PRIMITIVE_CELL_VOLUME = float(abs(np.linalg.det(_M)))  # = 1/sqrt(2)


# ---------------------------------------------------------------------------
# Twelve nearest-neighbour offsets in index space.
#
# Derivation: world-space nearest neighbours are +-v_i and +-(v_i - v_j).
# In index space (basis {v1,v2,v3}) those become:
#   +-v_i           -> +-(1,0,0), +-(0,1,0), +-(0,0,1)
#   +-(v_i - v_j)   -> +-(1,-1,0), +-(0,1,-1), +-(1,0,-1)
#
# Stored int8 for compactness (fits in 24 bits per offset including padding).
# ---------------------------------------------------------------------------

_NEIGHBOURS = np.array(
    [
        # axial (6)
        ( 1,  0,  0),
        (-1,  0,  0),
        ( 0,  1,  0),
        ( 0, -1,  0),
        ( 0,  0,  1),
        ( 0,  0, -1),
        # diagonal (6)
        ( 1, -1,  0),
        (-1,  1,  0),
        ( 0,  1, -1),
        ( 0, -1,  1),
        ( 1,  0, -1),
        (-1,  0,  1),
    ],
    dtype=np.int8,
)
assert _NEIGHBOURS.shape == (12, 3)


# ---------------------------------------------------------------------------
# Public spec
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class FCCSpec:
    """Immutable description of the FCC lattice used by the simulator.

    All arrays are views into module-level constants; do not mutate them.
    """

    # Primitive-cell basis: ``world = M @ index``. Shape (3, 3), float64.
    M: np.ndarray = field(default_factory=lambda: _M)
    M_inv: np.ndarray = field(default_factory=lambda: _M_INV)

    # Volume of one primitive cell in world units (= 1/sqrt(2) by construction).
    primitive_cell_volume: float = _PRIMITIVE_CELL_VOLUME

    # Index-space offsets to the 12 nearest neighbours. Shape (12, 3), int8.
    neighbours: np.ndarray = field(default_factory=lambda: _NEIGHBOURS)

    # Nearest-neighbour distance in world units (= 1 by construction).
    nn_distance: float = 1.0

    @property
    def n_neighbours(self) -> int:
        return int(self.neighbours.shape[0])

    # ------------------------------------------------------------------
    # Coordinate transforms
    # ------------------------------------------------------------------

    def index_to_world(self, idx: np.ndarray) -> np.ndarray:
        """Map index-space coordinates to world-space coordinates.

        Accepts shape (3,) or (..., 3). Returns the same shape.
        """
        idx = np.asarray(idx, dtype=np.float64)
        return idx @ self.M.T  # equivalent to (M @ idx.T).T for batched inputs

    def world_to_index(self, world: np.ndarray) -> np.ndarray:
        """Inverse of :meth:`index_to_world`. Returns float coordinates;
        the caller decides whether to round or interpolate."""
        world = np.asarray(world, dtype=np.float64)
        return world @ self.M_inv.T

    # ------------------------------------------------------------------
    # Storage helpers
    # ------------------------------------------------------------------

    @staticmethod
    def cell_count(shape: Tuple[int, int, int]) -> int:
        """Number of real cells in a field of the given index-space shape.

        For dense storage this is just the product of the dimensions. Provided
        as a method so callers do not assume the implementation; if BCC is
        added later, that lattice's spec can override this.
        """
        a, b, c = shape
        return int(a) * int(b) * int(c)

    def physical_volume(self, shape: Tuple[int, int, int]) -> float:
        """World-space volume occupied by a field of the given shape."""
        return self.primitive_cell_volume * self.cell_count(shape)

    # ------------------------------------------------------------------
    # GLSL header
    # ------------------------------------------------------------------

    def glsl_header(self) -> str:
        """Return a GLSL source fragment that defines lattice constants.

        Inject this near the top of every compute/fragment shader that needs
        neighbour offsets or the index-to-world transform. The header is
        self-contained and depends on nothing.
        """
        return _glsl_header_text()


def _format_mat3_glsl(M: np.ndarray) -> str:
    """Emit a GLSL ``mat3`` literal in column-major order (GLSL convention)."""
    cols = [M[:, i] for i in range(3)]
    parts = []
    for col in cols:
        parts.append(f"vec3({col[0]:.17g}, {col[1]:.17g}, {col[2]:.17g})")
    return "mat3(\n        " + ",\n        ".join(parts) + "\n    )"


def _glsl_header_text() -> str:
    n = _NEIGHBOURS.shape[0]
    offs = ",\n        ".join(
        f"ivec3({int(o[0])}, {int(o[1])}, {int(o[2])})" for o in _NEIGHBOURS
    )
    m_lit = _format_mat3_glsl(_M)
    minv_lit = _format_mat3_glsl(_M_INV)
    return f"""\
// ---------------------------------------------------------------------------
// FCC lattice header (generated by lattice.py - do not edit manually)
// ---------------------------------------------------------------------------
// Cells are stored densely in a 3D texture indexed by ivec3. The world-space
// position of cell (a, b, c) is LATTICE_M * vec3(a, b, c). The 12 nearest
// neighbours are unit-distance face neighbours of the rhombic-dodecahedron
// Wigner-Seitz cell.

#define LATTICE_FCC                    1
#define LATTICE_N_NEIGHBOURS           {n}
#define LATTICE_NN_DISTANCE            1.0
#define LATTICE_PRIMITIVE_CELL_VOLUME  {_PRIMITIVE_CELL_VOLUME:.17g}

const ivec3 LATTICE_NEIGHBOURS[LATTICE_N_NEIGHBOURS] = ivec3[LATTICE_N_NEIGHBOURS](
        {offs}
);

// Columns of LATTICE_M are the primitive lattice vectors v1, v2, v3.
const mat3 LATTICE_M     = {m_lit};
const mat3 LATTICE_M_INV = {minv_lit};

vec3 lattice_index_to_world(vec3 idx) {{ return LATTICE_M * idx; }}
vec3 lattice_world_to_index(vec3 w)   {{ return LATTICE_M_INV * w; }}
"""


# Module-level singleton. Import as `from lattice import FCC`.
FCC = FCCSpec()


# ---------------------------------------------------------------------------
# Self-checks (executed when running this file directly)
# ---------------------------------------------------------------------------


def _self_check() -> None:
    """Verify the lattice geometry is internally consistent."""
    fcc = FCC

    # 1. M is right-handed (positive determinant).
    det = np.linalg.det(fcc.M)
    assert det > 0, f"basis must be right-handed; got det(M) = {det}"

    # 2. Primitive vectors are unit length.
    for i in range(3):
        col = fcc.M[:, i]
        assert np.isclose(np.linalg.norm(col), 1.0), (
            f"v{i + 1} must be unit length; got |v{i + 1}| = {np.linalg.norm(col)}"
        )

    # 3. All 12 neighbours are unique.
    s = {tuple(int(x) for x in row) for row in fcc.neighbours}
    assert len(s) == 12, f"expected 12 unique offsets, got {len(s)}"

    # 4. Every neighbour offset maps to a unit-distance world vector.
    for off in fcc.neighbours:
        w = fcc.index_to_world(off)
        d = float(np.linalg.norm(w))
        assert np.isclose(d, 1.0), (
            f"neighbour offset {tuple(int(x) for x in off)} -> world {w}, |w| = {d} (expected 1.0)"
        )

    # 5. Neighbour set is symmetric (for every +o there is a -o).
    neg_set = {tuple(int(-x) for x in row) for row in fcc.neighbours}
    assert s == neg_set, "neighbour set must be symmetric under negation"

    # 6. M_inv really inverts M.
    eye = fcc.M @ fcc.M_inv
    assert np.allclose(eye, np.eye(3), atol=1e-12), "M_inv does not invert M"

    # 7. Round-trip a random batch of points through index<->world.
    rng = np.random.default_rng(0)
    pts = rng.uniform(-10.0, 10.0, size=(64, 3))
    rt = fcc.index_to_world(fcc.world_to_index(pts))
    assert np.allclose(pts, rt, atol=1e-10), "world -> index -> world must round-trip"

    # 8. Cell-count helper is just the product (dense storage).
    assert fcc.cell_count((4, 5, 6)) == 120

    # 9. Primitive cell volume matches 1/sqrt(2).
    assert np.isclose(fcc.primitive_cell_volume, 1.0 / np.sqrt(2.0))

    # 10. GLSL header is non-empty, mentions the key macros, parses as ASCII.
    h = fcc.glsl_header()
    for tok in (
        "LATTICE_FCC",
        "LATTICE_N_NEIGHBOURS",
        "LATTICE_NEIGHBOURS",
        "LATTICE_M",
        "LATTICE_M_INV",
        "lattice_index_to_world",
        "lattice_world_to_index",
    ):
        assert tok in h, f"GLSL header missing token: {tok}"
    h.encode("ascii")  # raises if any non-ASCII slipped in

    print("lattice.py self-check: OK")
    print(f"  primitive cell volume = {fcc.primitive_cell_volume:.6f} (= 1/sqrt(2))")
    print(f"  neighbours = {fcc.n_neighbours} (all unit-distance)")
    print(f"  det(M) = {det:.6f}  (right-handed)")
    print(f"  GLSL header = {len(h)} chars")


if __name__ == "__main__":
    _self_check()
